sonar.organization=elidjeidevoper-startup
sonar.projectKey=elidjeidevoper-startup_diario-de-poemas
sonar.projectName=diario-de-poemas

# Define que o código fonte principal está na pasta app
sonar.sources=app

# Ignora pastas de dependências e builds para a análise não falhar ou demorar muito
sonar.exclusions=node_modules/**, .next/**, out/**
sonar.coverage.exclusions=**/*